In [3]:
import pandas as pd

red_wine = pd.read_csv(r"C:\Users\cumdi\Desktop\Bootcamp Visual Studio\Modul 1\Project_02\windedata\winequality-red.csv", sep =";")
red_wine.tail(10)
#C:\Users\cumdi\Desktop\Bootcamp Visual Studio\Modul 1\Project_02\windedata\winequality-red.csv
# SEP-Argument seperiert die Daten, hier ist es  mit einem Semicolon

white_wine = pd.read_csv(r"C:\Users\cumdi\Desktop\Bootcamp Visual Studio\Modul 1\Project_02\windedata\winequality-white.csv", sep =";")

In [4]:
red_wine.tail(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1589,6.6,0.725,0.20,7.8,0.073,29.0,79.0,0.99770,3.29,0.54,9.2,5
1590,6.3,0.550,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6
1591,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6
1592,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1593,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [5]:
white_wine.tail(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
4888,6.8,0.220,0.36,1.20,0.052,38.0,127.0,0.99330,3.04,0.54,9.2,5
4889,4.9,0.235,0.27,11.75,0.030,34.0,118.0,0.99540,3.07,0.50,9.4,6
4890,6.1,0.340,0.29,2.20,0.036,25.0,100.0,0.98938,3.06,0.44,11.8,6
4891,5.7,0.210,0.32,0.90,0.038,38.0,121.0,0.99074,3.24,0.46,10.6,6
4892,6.5,0.230,0.38,1.30,0.032,29.0,112.0,0.99298,3.29,0.54,9.7,5
4893,6.2,0.210,0.29,1.60,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.320,0.36,8.00,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.240,0.19,1.20,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.290,0.30,1.10,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.210,0.38,0.80,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

### Shape messen

In [6]:
print(f"{"Shapefunktion: Wir haben " } {white_wine.shape[0]} {" Zeilen und "}{white_wine.shape[1]} {" Spalten"}")
#print(f"Standardabweichung: {standardabweichung:.2f}")

Shapefunktion: Wir haben  4898  Zeilen und 12  Spalten

### Werte prüfen auf Fehlstellen & NAN Werte

In [7]:

#na_matrix = Weisswein.isna()

#print(na_matrix)
#anzahl der Nan Werte'
nan_count = white_wine.isna().sum().sum()

if nan_count == 0:
        print(f"Es gibt {nan_count} keine Fehler")
else:
        print(f"Es gibt {nan_count} Fehler")


        #print(f"Standardabweichung: {standardabweichung:.2f}")

Es gibt 0 keine Fehler

### Describe

In [8]:
white_wine.describe

<bound method NDFrame.describe of       fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045
1               6.3              0.30         0.34             1.6      0.049
2               8.1              0.28         0.40             6.9      0.050
3               7.2              0.23         0.32             8.5      0.058
4               7.2              0.23         0.32             8.5      0.058
...             ...               ...          ...             ...        ...
4893            6.2              0.21         0.29             1.6      0.039
4894            6.6              0.32         0.36             8.0      0.047
4895            6.5              0.24         0.19             1.2      0.041
4896            5.5              0.29         0.30             1.1      0.022
4897            6.0              0.21         0.38             0.8      0.020

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45
1                    14.0                 132.0  0.99400  3.30       0.49
2                    30.0                  97.0  0.99510  3.26       0.44
3                    47.0                 186.0  0.99560  3.19       0.40
4                    47.0                 186.0  0.99560  3.19       0.40
...                   ...                   ...      ...   ...        ...
4893                 24.0                  92.0  0.99114  3.27       0.50
4894                 57.0                 168.0  0.99490  3.15       0.46
4895                 30.0                 111.0  0.99254  2.99       0.46
4896                 20.0                 110.0  0.98869  3.34       0.38
4897                 22.0                  98.0  0.98941  3.26       0.32

      alcohol  quality
0         8.8        6
1         9.5        6
2        10.1        6
3         9.9        6
4         9.9        6
...       ...      ...
4893     11.2        6
4894      9.6        5
4895      9.4        6
4896     12.8        7
4897     11.8        6

[4898 rows x 12 columns]>

### Let's now group our qualities into 3 categories: low, medium and high quality wines.

In [9]:
# we are creating a new column called "quality_label", we define a range and associate that range with a label
red_wine['quality_label'] = red_wine['quality'].apply(lambda value: 'low'
if value <= 5 else 'medium'
if value <= 7 else 'high')

# here we are transforming these labels into a categorical data type (specific to pandas) instead of a simple string
red_wine['quality_label'] = pd.Categorical(red_wine['quality_label'],
categories=['low', 'medium', 'high'])

In [10]:
# we are creating a new column called "quality_label", we define a range and associate that range with a label
white_wine['quality_label'] = white_wine['quality'].apply(lambda value: 'low'
if value <= 5 else 'medium'
if value <= 7 else 'high')

# here we are transforming these labels into a categorical data type (specific to pandas) instead of a simple string
white_wine['quality_label'] = pd.Categorical(white_wine['quality_label'],
categories=['low', 'medium', 'high'])

In [11]:
red_wine.tail(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,quality_label
1589,6.6,0.725,0.20,7.8,0.073,29.0,79.0,0.99770,3.29,0.54,9.2,5,low
1590,6.3,0.550,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6,medium
1591,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6,medium
1592,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,medium
1593,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,medium
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,low
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,medium
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,medium
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,low
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,medium

In [12]:
white_wine.tail(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,quality_label
4888,6.8,0.220,0.36,1.20,0.052,38.0,127.0,0.99330,3.04,0.54,9.2,5,low
4889,4.9,0.235,0.27,11.75,0.030,34.0,118.0,0.99540,3.07,0.50,9.4,6,medium
4890,6.1,0.340,0.29,2.20,0.036,25.0,100.0,0.98938,3.06,0.44,11.8,6,medium
4891,5.7,0.210,0.32,0.90,0.038,38.0,121.0,0.99074,3.24,0.46,10.6,6,medium
4892,6.5,0.230,0.38,1.30,0.032,29.0,112.0,0.99298,3.29,0.54,9.7,5,low
4893,6.2,0.210,0.29,1.60,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,medium
4894,6.6,0.320,0.36,8.00,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,low
4895,6.5,0.240,0.19,1.20,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,medium
4896,5.5,0.290,0.30,1.10,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,medium
4897,6.0,0.210,0.38,0.80,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,medium

#Combine both
pd.concat([red_wine.describe(), white_wine.describe()], axis=1, keys=["Red Wines Stats", "White Wines Stats"])

In [ ]:
redandwhite = pd.concat([red_wine.describe(), white_wine.describe()], axis=1, keys=["Red Wines Stats", "White Wines Stats"])
redandwhite.tail

<bound method NDFrame.tail of       Red Wines Stats                                               \
        fixed acidity volatile acidity  citric acid residual sugar
count     1599.000000      1599.000000  1599.000000    1599.000000
mean         8.319637         0.527821     0.270976       2.538806
std          1.741096         0.179060     0.194801       1.409928
min          4.600000         0.120000     0.000000       0.900000
25%          7.100000         0.390000     0.090000       1.900000
50%          7.900000         0.520000     0.260000       2.200000
75%          9.200000         0.640000     0.420000       2.600000
max         15.900000         1.580000     1.000000      15.500000

                                                                          \
         chlorides free sulfur dioxide total sulfur dioxide      density
count  1599.000000         1599.000000          1599.000000  1599.000000
mean      0.087467           15.874922            46.467792     0.996747
std       0.047065           10.460157            32.895324     0.001887
min       0.012000            1.000000             6.000000     0.990070
25%       0.070000            7.000000            22.000000     0.995600
50%       0.079000           14.000000            38.000000     0.996750
75%       0.090000           21.000000            62.000000     0.997835
max       0.611000           72.000000           289.000000     1.003690

                                 ... White Wines Stats                 \
                pH    sulphates  ...       citric acid residual sugar
count  1599.000000  1599.000000  ...       4898.000000    4898.000000
mean      3.311113     0.658149  ...          0.334192       6.391415
std       0.154386     0.169507  ...          0.121020       5.072058
min       2.740000     0.330000  ...          0.000000       0.600000
25%       3.210000     0.550000  ...          0.270000       1.700000
50%       3.310000     0.620000  ...          0.320000       5.200000
75%       3.400000     0.730000  ...          0.390000       9.900000
max       4.010000     2.000000  ...          1.660000      65.800000

                                                                          \
         chlorides free sulfur dioxide total sulfur dioxide      density
count  4898.000000         4898.000000          4898.000000  4898.000000
mean      0.045772           35.308085           138.360657     0.994027
std       0.021848           17.007137            42.498065     0.002991
min       0.009000            2.000000             9.000000     0.987110
25%       0.036000           23.000000           108.000000     0.991723
50%       0.043000           34.000000           134.000000     0.993740
75%       0.050000           46.000000           167.000000     0.996100
max       0.346000          289.000000           440.000000     1.038980


                pH    sulphates      alcohol      quality
count  4898.000000  4898.000000  4898.000000  4898.000000
mean      3.188267     0.489847    10.514267     5.877909
std       0.151001     0.114126     1.230621     0.885639
min       2.720000     0.220000     8.000000     3.000000
25%       3.090000     0.410000     9.500000     5.000000
50%       3.180000     0.470000    10.400000     6.000000
75%       3.280000     0.550000    11.400000     6.000000
max       3.820000     1.080000    14.200000     9.000000

[8 rows x 24 columns]>