## Wiederholung Modul 01 Sprint 4

### Data Wrangling

In [2]:
import pandas as pd
import numpy as np

movies_df = pd.read_csv("movies_2.csv" ) # Gathering data
movies_df.head(3) # head und tail Zeigen Anfang und Ende einer Tabelle an
movies_df.info

<bound method DataFrame.info of      MovieID                                  Title MPAA Rating       Budget  \
0          1                     Look Who's Talking       PG-13    7500000.0
1          2                     Driving Miss Daisy          PG    7500000.0
2          3                         Turner & Hooch          PG   13000000.0
3          4             Born on the Fourth of July           R   14000000.0
4          5                        Field of Dreams          PG   15000000.0
..       ...                                    ...         ...          ...
611      612                            Toy Story 4           G  200000000.0
612      613  Fast & Furious Presents: Hobbs & Shaw       PG-13  200000000.0
613      614                          The Lion King          PG  250000000.0
614      615                      Avengers: Endgame       PG-13  356000000.0
615        0                                    NaN         NaN          NaN

            Gross Release Date      Genre  Runtime  Rating  Rating Count  \
0    2.960000e+08   1989-10-12    Romance     93.0     5.9       73638.0
1    1.457933e+08   1989-12-13     Comedy     99.0     7.4       91075.0
2    7.107992e+07   1989-07-28      Crime    100.0     7.2       91415.0
3    1.610017e+08   1989-12-20        War    145.0     7.2       91415.0
4    8.443162e+07   1989-04-21      Drama    107.0     7.5      101702.0
..            ...          ...        ...      ...     ...           ...
611  1.062000e+09   2019-06-11  Animation    100.0     NaN           NaN
612  7.594000e+08   2019-07-13   Thriller    136.0     NaN           NaN
613  1.632000e+09   2019-07-09      Drama    118.0     NaN           NaN
614  2.796000e+09   2019-04-22     Action    181.0     NaN           NaN
615           NaN          NaN        NaN      NaN     NaN           NaN

                                               Summary
0    After a single, career-minded woman is left on...
1    An old Jewish woman and her African-American c...
2    Det. Scott Turner (Tom Hanks) is an uptight, b...
3    The biography of Ron Kovic. Paralyzed in the V...
4    An Iowa corn farmer, hearing voices, interpret...
..                                                 ...
611                                                NaN
612                                                NaN
613                                                NaN
614                                                NaN
615                                                NaN

[616 rows x 11 columns]>

### Find missing Values - 2 Schreibweisen

In [3]:
movies_df["Rating"].isna().value_counts() # kurzer Befehle
missing_values = movies_df["Rating"].isna().value_counts() # dasselbe in etwas ausfÃ¼hrlicheren Form
print(f"Anzahl der fehlenden Werte (NaN): {missing_values[True]}")
print(f"Anzahl der vorhandenen Werte: {missing_values[False]}")

Anzahl der fehlenden Werte (NaN): 108
Anzahl der vorhandenen Werte: 508

### Fillna Methode:

### a) Mit 2 Schritten> erst Median dann Fillna

### b) 1 Schritt mit neuer Variable

### c) Fillna mit inplace True- warnt aber

In [4]:

#a) Median dann Fillna

#medianrating = movies_df['Rating'].median() #ermittelt den Median
#medianrating

#fillnamovies = movies_df["Rating"].fillna(medianrating)
#fillnamovies.tail(3)

In [5]:
# fillnamovieszwei = movies_df["Rating"].fillna(movies_df['Rating'].median())
# fillnamovieszwei
# fillnamovieszwei.tail(3)

# In einem Schritt aber mit neuer Variable:
#fillnamovieszwei = movies_df["Rating"].fillna(movies_df['Rating'].median())

# c)behalten der Variable movies_df:
movies_df["Rating"].fillna(movies_df['Rating'].median(), inplace=True)

movies_df.tail(3) 


# um warnung zu Vermeiden gibts eine Methode um inplace True 
# genauer zu beschreiben: 
# movies_df["Rating"] = movies_df["Rating"].fillna(movies_df['Rating'].median())

C:\Users\cumdi\AppData\Local\Temp\ipykernel_9188\121760200.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies_df["Rating"].fillna(movies_df['Rating'].median(), inplace=True)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,6.9,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,6.9,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.9,NaN,NaN

letzte Zeile lÃ¶schen:

In [6]:
#movies_df(index=615).drop(inplace = True)

# Zeile lÃ¶schen: df.drop(['ID-123', 'ID-707'], axis=0) #Beispiel aus dem Netz

  
#movies_df.drop(index = 615) # lÃ¶scht letzte Zeile

In [8]:
movies_df.tail(3)

movies_df[600:]

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
600,601,The Secret Life of Pets 2,PG,80000000.0,4.294000e+08,2019-05-24,Animation,86.0,6.9,NaN,NaN
601,602,Once Upon a Time in Hollywood,R,96000000.0,3.459000e+08,2019-05-21,Comedy,161.0,6.9,NaN,NaN
602,603,The LEGO Movie 2: The Second Part,PG,99000000.0,1.913000e+08,2019-02-07,Animation,107.0,6.9,NaN,NaN
603,604,Shazam!,PG-13,100000000.0,3.650000e+08,2019-03-15,Action,132.0,6.9,NaN,NaN
604,605,How to Train Your Dragon: The Hidden World,PG,129000000.0,5.199000e+08,2019-01-03,Animation,104.0,6.9,NaN,NaN
605,606,Pokemon Detective Pikachu,PG,150000000.0,4.316000e+08,2019-05-03,Mystery,104.0,6.9,NaN,NaN
606,607,Spider-Man: Far from Home,PG-13,160000000.0,1.131000e+09,2019-06-26,Action,129.0,6.9,NaN,NaN
607,608,Dumbo,PG,170000000.0,3.530000e+08,2019-03-11,Adventure,112.0,6.9,NaN,NaN
608,609,Captain Marvel,PG-13,175000000.0,1.128000e+09,2019-02-27,Action,124.0,6.9,NaN,NaN
609,610,Aladdin,PG,183000000.0,1.049000e+09,2019-05-08,Fantasy,128.0,6.9,NaN,NaN
610,611,Godzilla: King of the Monsters,PG-13,200000000.0,3.859000e+08,2019-05-13,Adventure,132.0,6.9,NaN,NaN
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,6.9,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,6.9,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,6.9,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,6.9,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.9,NaN,NaN