## ***Summary of Sprint 4***

In [2]:
import pandas as pd
import numpy as np

movies_df = pd.read_csv("movies_2.csv" ) # Gathering data
movies_df.head(10)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
5,6,Uncle Buck,PG,15000000.0,79258538.0,1989-08-16,Family,100.0,7.0,77659.0,Bachelor and all-round slob Buck babysits his ...
6,7,When Harry Met Sally...,R,16000000.0,92800000.0,1989-07-21,Romance,96.0,7.6,180871.0,Harry and Sally have known each other for year...
7,8,Dead Poets Society,PG,16400000.0,235860116.0,1989-06-02,Drama,129.0,8.1,382002.0,English teacher John Keating inspires his stud...
8,9,Parenthood,PG-13,20000000.0,126297830.0,1989-07-31,Comedy,124.0,7.0,41866.0,The Buckmans are a midwestern family all deali...
9,10,Lethal Weapon 2,R,25000000.0,227853986.0,1989-07-07,Comedy,114.0,7.2,151737.0,Riggs and Murtaugh are on the trail of South A...

In [3]:
movies_df

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#movies_df.drop("Summary", axis=1, inplace=True) #löschen der Spalte Summary #axis 1 ist column und axis 0 ist row?
# 
movies_df.tail()

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,NaN,NaN,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,NaN,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,NaN,NaN,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:

movies_df.columns = movies_df.columns.str.lower()
movies_df.head()
movies_df.rename(columns={'mpaa rating':'mpaa_rating'})
movies_df.rename(columns={'release date':'release_date'})

movies_df.head()

movies_df.fillna({"rating":movies_df["rating"].median()},inplace=True) # Marcs Lösung
movies_df.head()

,movieid,title,mpaa rating,budget,gross,release date,genre,runtime,rating,rating count,summary
0,1,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."

## Duplikate finden

In [6]:
#movies_df[movies_df["title"].duplicate(keep = False)] #Marcs Code

## String to Integer

In [19]:
movies_df["budget"]
#movies_df.drop(movies_df.index[-1], axis=0, inplace=True)
#movies_df.iloc[-1:] #zeigt letzte Zeile an

0        7500000.0
1        7500000.0
2       13000000.0
3       14000000.0
4       15000000.0
          ...
611    200000000.0
612    200000000.0
613    250000000.0
614    356000000.0
615            NaN
Name: budget, Length: 616, dtype: float64

Date

In [20]:
movies_df.rename(columns={'release date':'release_date'})

,movieid,title,mpaa rating,budget,gross,release_date,genre,runtime,rating,rating_count,summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,6.9,240347.5,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,6.9,240347.5,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,6.9,240347.5,NaN
614,615,Avengers: Endgame,PG-13,356000000.0,2.796000e+09,2019-04-22,Action,181.0,6.9,240347.5,NaN
615,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.9,240347.5,NaN

In [21]:
#movies_df["release_date"] = pd.to_datetime(movies_df["release_date"]) #funktioniert nicht
#movies_df

In [40]:
movies_df.rename(columns={'mpaa rating':'mpaa_rating'},inplace=True) #inplace true is important!!!
movies_df.rename(columns={'release date':'release_date'},inplace=True)
movies_df

,movieid,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count,summary
0,1,Look Who's Talking,PG-13,7500000.0,2.960000e+08,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,1.457933e+08,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,7.107992e+07,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,1.610017e+08,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,8.443162e+07,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."
...,...,...,...,...,...,...,...,...,...,...,...
609,610,Aladdin,PG,183000000.0,1.049000e+09,2019-05-08,Fantasy,128.0,6.9,240347.5,NaN
610,611,Godzilla: King of the Monsters,PG-13,200000000.0,3.859000e+08,2019-05-13,Adventure,132.0,6.9,240347.5,NaN
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,6.9,240347.5,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,6.9,240347.5,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,6.9,240347.5,NaN

Rating count umbenennen und die leeren Stellen mit dem MEAN auffüllen

In [41]:
movies_df.rename(columns={'rating count':'rating_count'},inplace=True)
movies_df.fillna({"rating_count":movies_df["rating_count"].median()},inplace=True) # Marcs Lösung

movies_df.tail()

,movieid,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count,summary
609,610,Aladdin,PG,183000000.0,1.049000e+09,2019-05-08,Fantasy,128.0,6.9,240347.5,NaN
610,611,Godzilla: King of the Monsters,PG-13,200000000.0,3.859000e+08,2019-05-13,Adventure,132.0,6.9,240347.5,NaN
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,6.9,240347.5,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,6.9,240347.5,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,6.9,240347.5,NaN

### Budget und Gross  in integer umwandeln

In [42]:
movies_df.drop(movies_df.index[-1], axis=0, inplace=True)

In [43]:
movies_df.dtypes

movieid           int64
title            object
mpaa_rating      object
budget          float64
gross           float64
release_date     object
genre            object
runtime         float64
rating          float64
rating_count    float64
summary          object
dtype: object

Datum umwandeln

pandas.to_datetime(arg, errors='raise', dayfirst=False, yearfirst=False, utc=False, format=None, exact=<no_default>, unit=None, infer_datetime_format=<no_default>, origin='unix', cache=True)

In [ ]:
movies_df["release_date"] = pd.to_datetime(movies_df["release_date"]) # wichtig ist das pd!!!! pd.to_datetime!!
movies_df.dtypes

movieid                  int64
title                   object
mpaa_rating             object
budget                 float64
gross                  float64
release_date    datetime64[ns]
genre                   object
runtime                float64
rating                 float64
rating_count           float64
summary                 object
dtype: object

In [48]:
movies_df.tail()

,movieid,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count,summary
608,609,Captain Marvel,PG-13,175000000.0,1.128000e+09,2019-02-27,Action,124.0,6.9,240347.5,NaN
609,610,Aladdin,PG,183000000.0,1.049000e+09,2019-05-08,Fantasy,128.0,6.9,240347.5,NaN
610,611,Godzilla: King of the Monsters,PG-13,200000000.0,3.859000e+08,2019-05-13,Adventure,132.0,6.9,240347.5,NaN
611,612,Toy Story 4,G,200000000.0,1.062000e+09,2019-06-11,Animation,100.0,6.9,240347.5,NaN
612,613,Fast & Furious Presents: Hobbs & Shaw,PG-13,200000000.0,7.594000e+08,2019-07-13,Thriller,136.0,6.9,240347.5,NaN

Aufgabe 3

show the count of Animation movies with more than 7 in Rating (use the shape() method)

In [49]:
movies_df["genre"].value_counts()
#movies_df["runtime"].value_counts()

genre
Action             109
Comedy              99
Animation           87
Drama               65
Thriller            41
Science Fiction     37
Adventure           30
Family              29
Romance             28
Fantasy             27
Crime               17
Horror              14
Mystery             11
War                  9
Western              6
History              4
Name: count, dtype: int64

Exercise: show the top 5 movies based on Budget

In [68]:
#Filme die mehr als 180 Minuten Spielzeit haben
movies_df[movies_df["runtime"] > 180]

# Beispiel: pandas intro Emily:
# connect two conditions with |
# pets[(() & ()) | ()]
# pets[(pets["desexed"] == True) | (pets["animal"] == "cat")]
# pets[((pets["desexed"] == False) & (pets["babies"] == 0)) | (pets["animal"] == "cat")]

movies_df[(movies_df["rating"] < 8 ) & (movies_df["genre"] == "History")]

,movieid,title,mpaa_rating,budget,gross,release_date,genre,runtime,rating,rating_count,summary
180,181,Shakespeare in Love,R,25000000.0,289317794.0,1998-12-11,History,122.0,7.1,203939.0,"A young Shakespeare, out of ideas and short of..."
232,233,The Patriot,R,110000000.0,215294342.0,2000-06-28,History,165.0,7.2,241120.0,Peaceful farmer Benjamin Martin is driven to l...
458,459,Lincoln,PG-13,65000000.0,275293450.0,2012-11-09,History,149.0,7.3,232227.0,"As the American Civil War continues to rage, A..."

pandas.DataFrame.nlargest
DataFrame.nlargest(n, columns, keep='first')